unbind r
bind r source-file ~/.tmux.conf \; display "Tmux Config Relaoded"

set -g prefix C-a
bind-key f run-shell "tmux new-window -n session-select 'tmux-session'"
set -g base-index 1
set -g default-terminal "tmux-256color"
set -g status-style 'bg=default fg=#9a9c9d'
set -g status-right ''

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r o run-shell "~/.local/bin/tmux-session dotfiles"
